
const DEG_TO_RAD = Math.PI / 180;
const DURATION = (1.0 / 50);
const RIBBON_COUNT = 11;
const PAPER_COUNT = 95;
const RIBBON_PARTICLE_COUNT = 30;
const RIBBON_PARTICLE_DIST = 8.0;
const RIBBON_PARTICLE_THICK = 8.0;
const RIBBON_PARTICLE_ANGLE = 45;
const RIBBON_PARTICLE_MASS = 1;
const RIBBON_PARTICLE_DRAG = 0.05;
const COLORS = [
	['#df0049', '#660671'],
	['#00e857', '#005291'],
	['#2bebbc', '#05798a'],
	['#ffd200', '#b06c00']
];

let CONFIG = {
	DEG_TO_RAD: DEG_TO_RAD,
	DURATION: DURATION,
	RIBBON_COUNT: RIBBON_COUNT,
	PAPER_COUNT: PAPER_COUNT,
	RIBBON_PARTICLE_COUNT: RIBBON_PARTICLE_COUNT,
	RIBBON_PARTICLE_DIST: RIBBON_PARTICLE_DIST,
	RIBBON_PARTICLE_THICK: RIBBON_PARTICLE_THICK,
	RIBBON_PARTICLE_ANGLE: RIBBON_PARTICLE_ANGLE,
	RIBBON_PARTICLE_MASS: RIBBON_PARTICLE_MASS,
	RIBBON_PARTICLE_DRAG: RIBBON_PARTICLE_DRAG,
	COLORS: COLORS,
	COLOR_INDEX	: (colors) => Math.round(Math.random() * (colors.length - 1)),
};

export default CONFIG;